## Pandas

In [7]:
import pandas as pd
import numpy as np

In [15]:
np.arange(0,20).reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [23]:
## Create dataframe
df=pd.DataFrame(data=np.arange(0,20).reshape(4,5),index=["Row1","Row2","Row3","Row4"],
            columns=["Column1","Column2","Column3","Column4","Column5"])

In [27]:
df.head()

      Column1  Column2  Column3  Column4  Column5
Row1        0        1        2        3        4
Row2        5        6        7        8        9
Row3       10       11       12       13       14
Row4       15       16       17       18       19

In [29]:
df.tail()

      Column1  Column2  Column3  Column4  Column5
Row1        0        1        2        3        4
Row2        5        6        7        8        9
Row3       10       11       12       13       14
Row4       15       16       17       18       19

In [31]:
type(df)

pandas.core.frame.DataFrame

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, Row1 to Row4
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  4 non-null      int32
 1   Column2  4 non-null      int32
 2   Column3  4 non-null      int32
 3   Column4  4 non-null      int32
 4   Column5  4 non-null      int32
dtypes: int32(5)
memory usage: 112.0+ bytes

In [35]:
df.describe()

         Column1    Column2    Column3    Column4    Column5
count   4.000000   4.000000   4.000000   4.000000   4.000000
mean    7.500000   8.500000   9.500000  10.500000  11.500000
std     6.454972   6.454972   6.454972   6.454972   6.454972
min     0.000000   1.000000   2.000000   3.000000   4.000000
25%     3.750000   4.750000   5.750000   6.750000   7.750000
50%     7.500000   8.500000   9.500000  10.500000  11.500000
75%    11.250000  12.250000  13.250000  14.250000  15.250000
max    15.000000  16.000000  17.000000  18.000000  19.000000

In [ ]:
# Indexing
## Columname , rowindex[loc],rowindex columnindex number[.iloc]

In [37]:
df.head()

      Column1  Column2  Column3  Column4  Column5
Row1        0        1        2        3        4
Row2        5        6        7        8        9
Row3       10       11       12       13       14
Row4       15       16       17       18       19

In [45]:
df[['Column1','Column2','Column3']]

      Column1  Column2  Column3
Row1        0        1        2
Row2        5        6        7
Row3       10       11       12
Row4       15       16       17

In [49]:
# by using columname
# IN series only one row or column will be there
type(df['Column1'])

pandas.core.series.Series

In [55]:
df.loc['Row1']

Column1    0
Column2    1
Column3    2
Column4    3
Column5    4
Name: Row1, dtype: int32

In [57]:
type(df.loc['Row2'])

pandas.core.series.Series

In [59]:
# using rowindex name loc
df.loc[['Row1','Row3']]

      Column1  Column2  Column3  Column4  Column5
Row1        0        1        2        3        4
Row3       10       11       12       13       14

In [67]:
df.head()

      Column1  Column2  Column3  Column4  Column5
Row1        0        1        2        3        4
Row2        5        6        7        8        9
Row3       10       11       12       13       14
Row4       15       16       17       18       19

In [75]:
df.iloc[1:4,1:4]

      Column2  Column3  Column4
Row2        6        7        8
Row3       11       12       13
Row4       16       17       18

In [77]:
df.iloc[2:,3:]

      Column4  Column5
Row3       13       14
Row4       18       19

In [105]:
df.iloc[0:,0::4]

      Column1  Column5
Row1        0        4
Row2        5        9
Row3       10       14
Row4       15       19

In [107]:
df.iloc[:,1:]

      Column2  Column3  Column4  Column5
Row1        1        2        3        4
Row2        6        7        8        9
Row3       11       12       13       14
Row4       16       17       18       19

In [111]:
## Convert data frame into arrays
df.iloc[:,1:].values

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19]])

In [116]:
## operation 
#show null value
df.isnull().sum()

Column1    0
Column2    0
Column3    0
Column4    0
Column5    0
dtype: int64

In [124]:
df['Column2'].unique()

array([ 1,  6, 11, 16])

In [144]:
df[df['Column3']>2 ]

      Column1  Column2  Column3  Column4  Column5
Row2        5        6        7        8        9
Row3       10       11       12       13       14
Row4       15       16       17       18       19